config/routes.rb
Rails.application.routes.draw do
  get "sign_up" => "users#new"
  resource :session
  resources :users
  root 'static#index'
  resources :campaigns do
    resources :contributions
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  # associations
  # parent
  has_many :contributions, dependent: :destroy # kill associated contributions
  # upon campaign deletion

  # child

  # class-level methods
  def self.last_updated
    order("updated_at desc")
  end

  # instance-level methods
  def active?
    active == true
  end

  # validations
  validates :title, presence: true, length: { in: 1..50 }
  validates :description, length: { in: 1..200 }
  validates :amount_needed, numericality: { greater_than: 0 }
end

app/models/contribution.rb
class Contribution < ApplicationRecord
  # associations
  # parent

  # child
  belongs_to :campaign

  # class-level methods
  def self.last_created
    order("created_at desc")
  end

  # instance-level methods

  # validations
  validates :first_name, :last_name, presence: true
  validates :email,
    format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :first_name, :last_name, :email, presence: true

  validates :email,
    format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  def name
    self.first_name + " " + self.last_name
  end

  def self.authenticate(email, password)
    user = User.find_by(email: email)
    user && user.authenticate(password)
  end

  def current_user
    User.find(session[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def require_signin
    unless current_user
      redirect_to new_session_url, notice: "Please sign in first!"
    end
  end

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
  # adding helper_method allows it to be a healper method as well
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController

  def index
    @campaigns = Campaign.last_updated
  end

  def show
    @campaign = Campaign.find(params[:id])
  end

  def edit
    @campaign = Campaign.find(params[:id])
  end

  def update
    @campaign = Campaign.find(params[:id])
    if @campaign.update(campaign_params)
      flash[:notice] = "Campaign has been successfully updated!"
      redirect_to campaign_path(@campaign)
    else
      render 'edit'
    end
  end

  def new
    @campaign = Campaign.new
  end

  def create
    @campaign = Campaign.new(campaign_params)
    if @campaign.save
      flash[:notice] = "Campaign has been successfully created!"
      redirect_to campaign_path(@campaign)
    else
      render 'new'
    end
  end

  def destroy
    @campaign = Campaign.find(params[:id])
    @campaign.destroy
    redirect_to campaigns_path
  end

  private

  def campaign_params
    params.require(:campaign).
      permit(:title, :description, :amount_needed, :medical_partner, :active)
  end
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  before_action :set_campaign

  def index
    @contributions = @campaign.contributions
  end

  def new
    @contribution = @campaign.contributions.new
  end

  def create
    @contribution = @campaign.contributions.new(contribution_params)
    if @contribution.save
      flash[:notice] = "Boom! Thanks for your contribution."
      redirect_to campaign_path(@campaign)
    else
      render 'new'
    end
  end

  private

  def contribution_params
    params.require(:contribution).permit(:first_name, :last_name, :email, :note)
  end

  def set_campaign
    @campaign = Campaign.find(params[:campaign_id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    if user = User.authenticate(params[:email], params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome back, #{user.first_name}!"
      redirect_to user_path(user)
    else
      flash.now[:notice] = "Oops! That email/password combo doesn't match our records."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
    flash[:notice] = "Thanks for stopping by!"
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def index
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, except: [:new, :create]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: "Thanks for signing up, #{@user.first_name}!"
      session[:id] = @user.id
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.save
      redirect_to user_path(@user), notice: "Your account has successfully been updated, #{@user.first_name}!"
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    first_name = @user.first_name
    @user.delete && session[:user_id] = nil
    redirect_to root_path, notice: "Sorry to see you go, #{first_name}!"
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/contributions_helper.rb
module ContributionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/campaigns/_form.html.erb
<%= form_for(@campaign) do |f| %>
<%= render 'shared/errors', object: @campaign %>
  <p><%= f.label :title %></p>
  <p><%= f.text_area :title, cols: 40, rows: 1, autofocus: true %></p>
  <p><%= f.label :description %></p>
  <p><%= f.text_area :description, cols: 40, rows: 7 %></p>
  <p><%= f.label :amount_needed %></p>
  <p><%= f.number_field :amount_needed %></p>
  <p><%= f.label :medical_partner %></p>
  <p><%= f.text_area :medical_partner, cols: 40, rows: 1 %></p>
  <p><%= f.label :active? %> <%= f.check_box :active %></p>
  <p><%= f.submit %></p>
<% end %>

app/views/campaigns/edit.html.erb
<h1>Edit Campaign</h1>
<%= render 'form' %>

app/views/campaigns/index.html.erb
<h1>Active campaigns</h1>
<% @campaigns.each do |campaign| %>
  <% if campaign.active? %>
    <h2><%= link_to(campaign.title, campaign_path(campaign.id)) %></h2>
    <p><%= campaign.description %></p>
    <p><%= number_to_currency(campaign.amount_needed) %></p>
    <p><%= campaign.medical_partner %></p>
    <p><%= link_to "Contribute", new_campaign_contribution_path(campaign) %></p>
    <p><em>Updated <%= time_ago_in_words(campaign.updated_at) %> ago</em></p>
  <% end %>
<% end %>

app/views/campaigns/new.html.erb
<h1>Create a new campaign</h1>
<%= render 'form' %>

app/views/campaigns/show.html.erb
<h1><%= @campaign.title %></h1>
<p><%= @campaign.description %></p>
<p><%= number_to_currency(@campaign.amount_needed) %></p>
<p>In partnership with <%= @campaign.medical_partner %></p>
<p><%= link_to "Contribute", new_campaign_contribution_path(@campaign) %></p>
<% if @campaign.contributions.any? %>
  <h2>Contributor Notes:</h2>
  <% @campaign.contributions.each do |contribution| %>
    <p><%= contribution.first_name %> says "<%= "#{contribution.note}" %>"</p>
  <% end %>
<% end %>
<p><%= link_to("Go Back", campaigns_path) %> |
<%= link_to("Edit", edit_campaign_path(@campaign))%> |
<%= link_to("Delete", campaign_path(@campaign), method: :delete, data: {confirm: "Are you sure you want to delete this campaign?"}) %>
</p>

app/views/contributions/index.html.erb
<h1>Recent contributions for <%= @campaign.title %></h1>
<% @contributions.each do |contribution| %>
  <p><%= contribution.first_name %> <%= contribution.last_name %> says: </p>
  <p><%= contribution.note %>
<% end %>

app/views/contributions/new.html.erb
<h1>Add your contribution to <%= @campaign.title %> below:</h1>

<%= form_for([@campaign, @contribution]) do |f| %>
<%= render 'shared/errors', object: @contribution %>
  <p><%= f.label :first_name %></p>
  <p><%= f.text_field :first_name %></p>
  <p><%= f.label :last_name %></p>
  <p><%= f.text_field :last_name %></p>
  <p><%= f.label :email %></p>
  <p><%= f.text_field :email %></p>
  <p><%= f.label :note %></p>
  <p><%= f.text_area :note, placeholder: "Leave a short, sweet 'get well' note here", cols: 40, rows: 7 %></p>
  <%= f.submit %> | <%= link_to('Go back', campaign_path(@campaign)) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FidoFund</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p><%= flash[:notice] if flash[:notice] %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <p>Ah snap! We found <strong><%= pluralize(object.errors.count, 'error') %></strong> with your submission: </p>
  <% object.errors.full_messages.each do |m| %>
    <li><%= m %></li>
  <% end %>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<%= render 'shared/errors', object: @user %>
  <p><%= f.label :first_name %></p>
  <p><%= f.text_field :first_name, autofocus: true %></p>
  <p><%= f.label :last_name %></p>
  <p><%= f.text_field :last_name %></p>
  <p><%= f.label :email %></p>
  <p><%= f.text_field :email %></p>
  <p><%= f.label :password %></p>
  <p><%= f.password_field :password, cols: 40, rows: 1 %></p>
  <p><%= f.label :password_confirmation, "Confirm password" %></p>
  <p><%= f.password_field :password_confirmation, cols: 40, rows: 1 %></p>
  <% if @user.new_record? %>
    <p><%= f.submit "Create account" %></p>
  <% else %>
    <p><%= f.submit "Update account" %></p>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<h1>All users </h1>
<% @users.each do |user| %>
  <p><%= link_to user.name, user_path(user) %></p>
<% end %>

app/views/users/new.html.erb
<h1>New User Sign Up</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<p><%= link_to "Edit account", edit_user_path(@user) %></p>
<p><%= link_to "Delete account", user_path(@user), method: :delete, data: { confirm: "Are you sure you want to delete your account, #{@user.first_name}?"} %>